### ISSUE TITLE
SNMP extension - Sequence 

### ISSUE THREAD

**Issue by PRASEETHAMS** [arunkrishnan-dt/dynatrace_snmp_2.0#1]
Hello Arun,

Did you encounter any issues like this in troubleshooting ? As error after excueting the signed package ?

Error as below -
WARN
Failed to assign monitoring configuration to Active Gate. Reason: Cannot extract extension from C:\WINDOWS\SERVIC1\LOCALS1\AppData\Local\Temp

**Comment by arunkrishnan-dt** [comment]
Hello, Yeah, I  have seen this with certificate related errors. Can you confirm if `ca.pem` file has been [copied to ActiveGate server](https://github.com/arunkrishnan-dt/dynatrace_snmp_2.0/blob/main/3_Sign_extension.md#upload-capem-to-activegates)?. Also, are you using `dt-cli` utility to generate certs and sign extension?

**Comment by PRASEETHAMS** [comment]
Hello Arun

Yes  I used the dt-cli and created both the certificates.
As per the procedure I also uploaded in the Active gate
***@***.***
While the ca.pem file was loaded to the  tenancy I saw this error below -did you see this in your case ?

PEM client certificate format requires Active Gates version 195 or higher

I didn't get any other exceptions anywhere.

Also I am using the snmp simulator and hence the local machine is given as the IP for adding the monitoring.
But in yours I see the IP 10.10.10.12 is it the IP of your device or the simulator reference you have ?


Cheers,
PraseethaMS

**Comment by arunkrishnan-dt** [comment]
Hey Praseetha, Apologies for the delay. Hope you were able to get this resolved! If it's still an issue, I would recommend contacting [Official Dynatrace Support](https://support.dynatrace.com/) (if not done already). They should be able to look at your specific issue and help.
Thank you, Arun

**Comment by PRASEETHAMS** [comment]
Hello Arun

I have a question. I saw you gave the IP address of a machine.
***@***.***

Say if we have more than 10 network devices we will have to repeat giving these IP address of those machines which we intend to monitor I suppose and keep adding the monitoring.
Is it a must that we need to have some criteria's on those end network machines - apart from the fact that it needs to be connected with Active gate ?

In my testing case I was using my local host as the simulator and the active gate together; so I didn't have chance to test with real machines >1 devices.

Cheers,
PraseethaMS

**Comment by arunkrishnan-dt** [comment]
Hey, There are  few things you will need to do on network device, depending on setup. A network admin should be able to help with it. Some items I can this of are:
1. SNMP must be enabled on network device
2. Create a SNMP Community string on network device
3. Whitelist IP addresses that can make SNMP requests to network devices (in some cases)

Thank you,
Arun
